import { POE2_BASES_GROUPED } from "@/lib/coe-lookup";

/**
 * Build a compact markdown section listing every authoritative PoE2 base item
 * grouped by category. Injected into the Oracle's system prompt so it cannot
 * hallucinate base names that don't exist in PoE2 (the recurring "Crude
 * Crossbow" / "Sadist Garb" failure mode — both are made-up names that
 * pattern-match from PoE1 or training data).
 *
 * Source: craftofexile.com/?game=poe2 (the community-accepted authority).
 * Regenerated by scripts/build-coe-lookup.mjs.
 */
export function buildBasesPromptSection(): string {
  const cats = Object.keys(POE2_BASES_GROUPED).sort();
  let totalBases = 0;
  let body = "";
  for (const cat of cats) {
    const list = POE2_BASES_GROUPED[cat];
    if (!list.length) continue;
    totalBases += list.length;
    body += `### ${cat} (${list.length})\n${list.join(", ")}\n\n`;
  }

  return `## Authoritative PoE2 Base Items — use ONLY names from this list

When you recommend a specific base in any craft response, you MUST pick from the lists below. These names are sourced from craftofexile.com/?game=poe2 (the authoritative community source) and represent every base that legally exists in patch 0.4.

**DO NOT invent base names.** Common failure modes to avoid:
- "Crude Crossbow" — does NOT exist. Real PoE2 crossbows include Makeshift Crossbow, Tense Crossbow, Sturdy Crossbow.
- "Sadist Garb" — does NOT exist. Real PoE2 INT body armours include Tattered Robe, Silk Robe, Imperial Robe.
- Any PoE1 name like "Spine Bow", "Vaal Regalia", "Astral Plate" — do NOT use these.

If the user asks about a base you don't recognize, pick the closest valid base from the list below and explain the substitution. NEVER fabricate.

There are ${totalBases} valid bases across ${cats.length} categories:

${body.trim()}
`;
}
