// AUTO-GENERATED by scripts/build-coe-lookup.mjs — do not edit by hand.
// Source: https://www.craftofexile.com/json/poe2/main/poec_data.json
// Generated: 2026-05-22T20:31:55.008Z
// Bases: 76 categories, 979 specific items
// Essences: 81

/** id_base for a Craft of Exile base CATEGORY (e.g. "Bow" → 20). */
export const COE_BASE_CATEGORIES: Record<string, { b: number }> = {
  "Abyss Precursor Tablet": {
    "b": 243
  },
  "Amulet": {
    "b": 2
  },
  "Belt": {
    "b": 3
  },
  "Body Armour (DEX)": {
    "b": 46
  },
  "Body Armour (DEX/INT)": {
    "b": 50
  },
  "Body Armour (INT)": {
    "b": 47
  },
  "Body Armour (STR)": {
    "b": 45
  },
  "Body Armour (STR/DEX)": {
    "b": 48
  },
  "Body Armour (STR/INT)": {
    "b": 49
  },
  "Boots (DEX)": {
    "b": 40
  },
  "Boots (DEX/INT)": {
    "b": 44
  },
  "Boots (INT)": {
    "b": 41
  },
  "Boots (STR)": {
    "b": 39
  },
  "Boots (STR/DEX)": {
    "b": 42
  },
  "Boots (STR/INT)": {
    "b": 43
  },
  "Bow": {
    "b": 20
  },
  "Breach Precursor Tablet": {
    "b": 237
  },
  "Chaos Staff": {
    "b": 226
  },
  "Chaos Wand": {
    "b": 218
  },
  "Charm": {
    "b": 241
  },
  "Claw": {
    "b": 11
  },
  "Crossbow": {
    "b": 228
  },
  "Dagger": {
    "b": 12
  },
  "Delirium Precursor Tablet": {
    "b": 239
  },
  "Emerald": {
    "b": 27
  },
  "Expedition Precursor Tablet": {
    "b": 240
  },
  "Fire Staff": {
    "b": 223
  },
  "Fire Wand": {
    "b": 220
  },
  "Flail": {
    "b": 217
  },
  "Focus": {
    "b": 229
  },
  "Gloves (DEX)": {
    "b": 34
  },
  "Gloves (DEX/INT)": {
    "b": 38
  },
  "Gloves (INT)": {
    "b": 35
  },
  "Gloves (STR)": {
    "b": 33
  },
  "Gloves (STR/DEX)": {
    "b": 36
  },
  "Gloves (STR/INT)": {
    "b": 37
  },
  "Helmet (DEX)": {
    "b": 53
  },
  "Helmet (DEX/INT)": {
    "b": 57
  },
  "Helmet (INT)": {
    "b": 54
  },
  "Helmet (STR)": {
    "b": 52
  },
  "Helmet (STR/DEX)": {
    "b": 55
  },
  "Helmet (STR/INT)": {
    "b": 56
  },
  "Ice Staff": {
    "b": 224
  },
  "Ice Wand": {
    "b": 222
  },
  "Life Flask": {
    "b": 60
  },
  "Lightning Staff": {
    "b": 225
  },
  "Lightning Wand": {
    "b": 221
  },
  "Low Tier (1-5)": {
    "b": 233
  },
  "Mana Flask": {
    "b": 61
  },
  "Mid Tier (6-10)": {
    "b": 234
  },
  "One Hand Axe": {
    "b": 15
  },
  "One Hand Mace": {
    "b": 16
  },
  "One Hand Sword": {
    "b": 13
  },
  "Overseer Precursor Tablet": {
    "b": 242
  },
  "Physical Staff": {
    "b": 227
  },
  "Physical Wand": {
    "b": 219
  },
  "Precursor Tablet": {
    "b": 236
  },
  "Quiver": {
    "b": 4
  },
  "Ring": {
    "b": 1
  },
  "Ritual Precursor Tablet": {
    "b": 238
  },
  "Ruby": {
    "b": 26
  },
  "Sapphire": {
    "b": 28
  },
  "Sceptre": {
    "b": 17
  },
  "Shield (DEX)": {
    "b": 6
  },
  "Shield (STR)": {
    "b": 5
  },
  "Shield (STR/DEX)": {
    "b": 8
  },
  "Shield (STR/INT)": {
    "b": 9
  },
  "Spear": {
    "b": 216
  },
  "Staff": {
    "b": 21
  },
  "Talisman": {
    "b": 244
  },
  "Top Tier (11-16)": {
    "b": 235
  },
  "Two Hand Axe": {
    "b": 24
  },
  "Two Hand Mace": {
    "b": 23
  },
  "Two Hand Sword": {
    "b": 22
  },
  "Wand": {
    "b": 18
  },
  "Warstaff": {
    "b": 25
  }
};

/** id_bitem for a Craft of Exile specific item (e.g. "Crude Bow" → { b: 20, bi: 231 }).
 *  Includes the parent category id_base so URLs can fully pre-fill. */
export const COE_BITEMS: Record<string, { b: number; bi: number }> = {
  "Abyssal Signet": {
    "b": 1,
    "bi": 945
  },
  "Ashen Staff": {
    "b": 223,
    "bi": 782
  },
  "Azure Amulet": {
    "b": 2,
    "bi": 16
  },
  "Blazon Crest Shield": {
    "b": 9,
    "bi": 112
  },
  "Broadhead Quiver": {
    "b": 4,
    "bi": 37
  },
  "Chain Mail": {
    "b": 48,
    "bi": 571
  },
  "Changeling Talisman": {
    "b": 244,
    "bi": 972
  },
  "Corroded Longsword": {
    "b": 22,
    "bi": 261
  },
  "Crimson Amulet": {
    "b": 2,
    "bi": 15
  },
  "Crude Bow": {
    "b": 20,
    "bi": 231
  },
  "Crude Claw": {
    "b": 11,
    "bi": 132
  },
  "Distorted Amulet": {
    "b": 2,
    "bi": 944
  },
  "Dull Hatchet": {
    "b": 15,
    "bi": 172
  },
  "Dusk Amulet": {
    "b": 2,
    "bi": 894
  },
  "Dusk Ring": {
    "b": 1,
    "bi": 898
  },
  "Felled Greatclub": {
    "b": 23,
    "bi": 274
  },
  "Garment": {
    "b": 51,
    "bi": 642
  },
  "Glass Shank": {
    "b": 12,
    "bi": 145
  },
  "Gloam Amulet": {
    "b": 2,
    "bi": 895
  },
  "Gloam Ring": {
    "b": 1,
    "bi": 899
  },
  "Golden Blade": {
    "b": 13,
    "bi": 158
  },
  "Hardwood Spear": {
    "b": 216,
    "bi": 749
  },
  "Hardwood Targe": {
    "b": 8,
    "bi": 92
  },
  "Hermit Garb": {
    "b": 50,
    "bi": 619
  },
  "Iron Ring": {
    "b": 1,
    "bi": 2
  },
  "Lazuli Ring": {
    "b": 1,
    "bi": 3
  },
  "Leather Buckler": {
    "b": 6,
    "bi": 70
  },
  "Leather Vest": {
    "b": 46,
    "bi": 523
  },
  "Lesser Life Flask": {
    "b": 60,
    "bi": 856
  },
  "Lesser Mana Flask": {
    "b": 61,
    "bi": 865
  },
  "Linen Belt": {
    "b": 3,
    "bi": 27
  },
  "Makeshift Crossbow": {
    "b": 228,
    "bi": 790
  },
  "Penumbra Amulet": {
    "b": 2,
    "bi": 896
  },
  "Penumbra Ring": {
    "b": 1,
    "bi": 900
  },
  "Pilgrim Vestments": {
    "b": 49,
    "bi": 597
  },
  "Rattling Sceptre": {
    "b": 17,
    "bi": 210
  },
  "Rawhide Belt": {
    "b": 3,
    "bi": 26
  },
  "Rawhide Boots": {
    "b": 40,
    "bi": 433
  },
  "Ring": {
    "b": 1,
    "bi": 13
  },
  "Rough Greaves": {
    "b": 39,
    "bi": 418
  },
  "Rusted Cuirass": {
    "b": 45,
    "bi": 499
  },
  "Rusted Greathelm": {
    "b": 52,
    "bi": 644
  },
  "Shabby Hood": {
    "b": 53,
    "bi": 663
  },
  "Shortsword": {
    "b": 13,
    "bi": 159
  },
  "Splintered Flail": {
    "b": 217,
    "bi": 762
  },
  "Splintered Tower Shield": {
    "b": 5,
    "bi": 48
  },
  "Splitting Greataxe": {
    "b": 24,
    "bi": 299
  },
  "Stocky Mitts": {
    "b": 33,
    "bi": 337
  },
  "Straw Sandals": {
    "b": 41,
    "bi": 448
  },
  "Suede Bracers": {
    "b": 34,
    "bi": 352
  },
  "Tattered Robe": {
    "b": 47,
    "bi": 547
  },
  "Tenebrous Amulet": {
    "b": 2,
    "bi": 897
  },
  "Tenebrous Ring": {
    "b": 1,
    "bi": 901
  },
  "Torn Gloves": {
    "b": 35,
    "bi": 367
  },
  "Twig Circlet": {
    "b": 54,
    "bi": 682
  },
  "Twig Focus": {
    "b": 229,
    "bi": 815
  },
  "Withered Wand": {
    "b": 218,
    "bi": 775
  },
  "Wooden Club": {
    "b": 16,
    "bi": 185
  },
  "Wrapped Quarterstaff": {
    "b": 25,
    "bi": 312
  },
  "Attuned Wand": {
    "b": 18,
    "bi": 225
  },
  "Bone Wand": {
    "b": 219,
    "bi": 777
  },
  "Gelid Staff": {
    "b": 224,
    "bi": 784
  },
  "Voltaic Staff": {
    "b": 225,
    "bi": 786
  },
  "Fur Plate": {
    "b": 45,
    "bi": 500
  },
  "Gauze Wraps": {
    "b": 38,
    "bi": 406
  },
  "Hook Axe": {
    "b": 15,
    "bi": 173
  },
  "Light Halberd": {
    "b": 24,
    "bi": 300
  },
  "Long Quarterstaff": {
    "b": 25,
    "bi": 313
  },
  "Medium Life Flask": {
    "b": 60,
    "bi": 857
  },
  "Medium Mana Flask": {
    "b": 61,
    "bi": 866
  },
  "Oak Greathammer": {
    "b": 23,
    "bi": 275
  },
  "Quilted Vest": {
    "b": 46,
    "bi": 524
  },
  "Smithing Hammer": {
    "b": 16,
    "bi": 186
  },
  "Tense Crossbow": {
    "b": 228,
    "bi": 791
  },
  "Brimmed Helm": {
    "b": 55,
    "bi": 701
  },
  "Feathered Robe": {
    "b": 47,
    "bi": 548
  },
  "Frayed Shoes": {
    "b": 44,
    "bi": 487
  },
  "Hewn Mask": {
    "b": 57,
    "bi": 733
  },
  "Iron Crown": {
    "b": 56,
    "bi": 717
  },
  "Ironhead Spear": {
    "b": 216,
    "bi": 750
  },
  "Nettle Talisman": {
    "b": 244,
    "bi": 973
  },
  "Padded Leggings": {
    "b": 43,
    "bi": 475
  },
  "Rope Cuffs": {
    "b": 37,
    "bi": 394
  },
  "Ruby Charm": {
    "b": 241,
    "bi": 889
  },
  "Sapphire Charm": {
    "b": 241,
    "bi": 890
  },
  "Shortbow": {
    "b": 20,
    "bi": 232
  },
  "Topaz Charm": {
    "b": 241,
    "bi": 891
  },
  "Wooden Buckler": {
    "b": 6,
    "bi": 71
  },
  "Broadsword": {
    "b": 13,
    "bi": 160
  },
  "Chain Flail": {
    "b": 217,
    "bi": 763
  },
  "Crone Knife": {
    "b": 12,
    "bi": 146
  },
  "Iron Greatsword": {
    "b": 22,
    "bi": 262
  },
  "Mail Sabatons": {
    "b": 42,
    "bi": 463
  },
  "Painted Tower Shield": {
    "b": 5,
    "bi": 49
  },
  "Pict Claw": {
    "b": 11,
    "bi": 133
  },
  "Ringmail Gauntlets": {
    "b": 36,
    "bi": 382
  },
  "Stoic Sceptre": {
    "b": 17,
    "bi": 211
  },
  "Woven Focus": {
    "b": 229,
    "bi": 816
  },
  "Sigil Crest Shield": {
    "b": 9,
    "bi": 113
  },
  "Amber Amulet": {
    "b": 2,
    "bi": 17
  },
  "Fire Quiver": {
    "b": 4,
    "bi": 38
  },
  "Jade Amulet": {
    "b": 2,
    "bi": 18
  },
  "Lapis Amulet": {
    "b": 2,
    "bi": 19
  },
  "Pearlescent Amulet": {
    "b": 2,
    "bi": 943
  },
  "Pelage Targe": {
    "b": 8,
    "bi": 93
  },
  "Ruby Ring": {
    "b": 1,
    "bi": 4
  },
  "Stone Charm": {
    "b": 241,
    "bi": 887
  },
  "Antler Focus": {
    "b": 229,
    "bi": 817
  },
  "Bearded Axe": {
    "b": 15,
    "bi": 174
  },
  "Cinderbark Talisman": {
    "b": 244,
    "bi": 974
  },
  "Executioner Greataxe": {
    "b": 24,
    "bi": 301
  },
  "Face Mask": {
    "b": 57,
    "bi": 734
  },
  "Felt Cap": {
    "b": 53,
    "bi": 664
  },
  "Greater Life Flask": {
    "b": 60,
    "bi": 858
  },
  "Greater Mana Flask": {
    "b": 61,
    "bi": 867
  },
  "Horned Crown": {
    "b": 56,
    "bi": 718
  },
  "Hunting Spear": {
    "b": 216,
    "bi": 751
  },
  "Pelt Mantle": {
    "b": 49,
    "bi": 598
  },
  "Silver Charm": {
    "b": 241,
    "bi": 888
  },
  "Slim Mace": {
    "b": 16,
    "bi": 187
  },
  "Sturdy Crossbow": {
    "b": 228,
    "bi": 792
  },
  "Wicker Tiara": {
    "b": 54,
    "bi": 683
  },
  "Blessed Claymore": {
    "b": 22,
    "bi": 263
  },
  "Firm Bracers": {
    "b": 34,
    "bi": 353
  },
  "Forge Maul": {
    "b": 23,
    "bi": 276
  },
  "Gothic Quarterstaff": {
    "b": 25,
    "bi": 314
  },
  "Guarded Helm": {
    "b": 55,
    "bi": 702
  },
  "Hexer's Robe": {
    "b": 47,
    "bi": 549
  },
  "Holy Flail": {
    "b": 217,
    "bi": 764
  },
  "Iron Cuirass": {
    "b": 45,
    "bi": 501
  },
  "Iron Greaves": {
    "b": 39,
    "bi": 419
  },
  "Laced Boots": {
    "b": 40,
    "bi": 434
  },
  "Pathfinder Coat": {
    "b": 46,
    "bi": 525
  },
  "Plated Buckler": {
    "b": 6,
    "bi": 72
  },
  "Riveted Mitts": {
    "b": 33,
    "bi": 338
  },
  "Rogue Armour": {
    "b": 48,
    "bi": 572
  },
  "Siphoning Wand": {
    "b": 18,
    "bi": 226
  },
  "Spriggan Staff": {
    "b": 21,
    "bi": 256
  },
  "Vampiric Blade": {
    "b": 13,
    "bi": 161
  },
  "Warden Bow": {
    "b": 20,
    "bi": 233
  },
  "Waxed Jacket": {
    "b": 50,
    "bi": 620
  },
  "Wrapped Sandals": {
    "b": 41,
    "bi": 449
  },
  "Braced Tower Shield": {
    "b": 5,
    "bi": 50
  },
  "Golden Hoop": {
    "b": 1,
    "bi": 1
  },
  "Golden Obi": {
    "b": 3,
    "bi": 25
  },
  "Lupine Sceptre": {
    "b": 17,
    "bi": 212
  },
  "Sapphire Ring": {
    "b": 1,
    "bi": 5
  },
  "Simple Dagger": {
    "b": 12,
    "bi": 147
  },
  "Soldier Greathelm": {
    "b": 52,
    "bi": 645
  },
  "Sombre Gloves": {
    "b": 35,
    "bi": 368
  },
  "Thawing Charm": {
    "b": 241,
    "bi": 882
  },
  "Wolfbone Claw": {
    "b": 11,
    "bi": 134
  },
  "Lunar Amulet": {
    "b": 2,
    "bi": 20
  },
  "Wide Belt": {
    "b": 3,
    "bi": 28
  },
  "Aged Cuffs": {
    "b": 37,
    "bi": 395
  },
  "Arched Greataxe": {
    "b": 24,
    "bi": 302
  },
  "Barricade Tower Shield": {
    "b": 5,
    "bi": 51
  },
  "Beaded Circlet": {
    "b": 54,
    "bi": 684
  },
  "Bone Raiment": {
    "b": 47,
    "bi": 550
  },
  "Bound Bracers": {
    "b": 34,
    "bi": 354
  },
  "Braced Sabatons": {
    "b": 42,
    "bi": 464
  },
  "Broad Greatsword": {
    "b": 22,
    "bi": 264
  },
  "Bronze Greaves": {
    "b": 39,
    "bi": 420
  },
  "Crackling Quarterstaff": {
    "b": 25,
    "bi": 315
  },
  "Cultist Crown": {
    "b": 56,
    "bi": 719
  },
  "Emblem Crest Shield": {
    "b": 9,
    "bi": 114
  },
  "Embossed Boots": {
    "b": 40,
    "bi": 435
  },
  "Engraved Focus": {
    "b": 229,
    "bi": 818
  },
  "Extended Cleaver": {
    "b": 15,
    "bi": 175
  },
  "Familial Talisman": {
    "b": 244,
    "bi": 975
  },
  "Forked Claw": {
    "b": 11,
    "bi": 135
  },
  "Grand Life Flask": {
    "b": 60,
    "bi": 859
  },
  "Grand Mana Flask": {
    "b": 61,
    "bi": 868
  },
  "Hooded Mask": {
    "b": 57,
    "bi": 735
  },
  "Iron Buckler": {
    "b": 6,
    "bi": 73
  },
  "Iron Flail": {
    "b": 217,
    "bi": 765
  },
  "Lace Hood": {
    "b": 53,
    "bi": 665
  },
  "Lattice Sandals": {
    "b": 41,
    "bi": 450
  },
  "Layered Gauntlets": {
    "b": 36,
    "bi": 383
  },
  "Linen Wraps": {
    "b": 38,
    "bi": 407
  },
  "Mail Vestments": {
    "b": 49,
    "bi": 599
  },
  "Marabout Garb": {
    "b": 50,
    "bi": 621
  },
  "Omen Sceptre": {
    "b": 17,
    "bi": 213
  },
  "Pyrophyte Staff": {
    "b": 223,
    "bi": 783
  },
  "Raider Plate": {
    "b": 45,
    "bi": 502
  },
  "Recurve Bow": {
    "b": 20,
    "bi": 234
  },
  "Sacral Quiver": {
    "b": 4,
    "bi": 39
  },
  "Scimitar": {
    "b": 13,
    "bi": 162
  },
  "Secured Leggings": {
    "b": 43,
    "bi": 476
  },
  "Shrouded Vest": {
    "b": 46,
    "bi": 526
  },
  "Skinning Knife": {
    "b": 12,
    "bi": 148
  },
  "Spiked Club": {
    "b": 16,
    "bi": 188
  },
  "Stitched Gloves": {
    "b": 35,
    "bi": 369
  },
  "Studded Greatclub": {
    "b": 23,
    "bi": 277
  },
  "Studded Targe": {
    "b": 8,
    "bi": 94
  },
  "Tempered Mitts": {
    "b": 33,
    "bi": 339
  },
  "Threaded Shoes": {
    "b": 44,
    "bi": 488
  },
  "Topaz Ring": {
    "b": 1,
    "bi": 6
  },
  "Vagabond Armour": {
    "b": 48,
    "bi": 573
  },
  "Varnished Crossbow": {
    "b": 228,
    "bi": 793
  },
  "Visored Helm": {
    "b": 55,
    "bi": 703
  },
  "Volatile Wand": {
    "b": 220,
    "bi": 779
  },
  "Winged Spear": {
    "b": 216,
    "bi": 752
  },
  "Wrapped Greathelm": {
    "b": 52,
    "bi": 646
  },
  "Bloodstone Amulet": {
    "b": 2,
    "bi": 21
  },
  "Staunching Charm": {
    "b": 241,
    "bi": 883
  },
  "Amethyst Ring": {
    "b": 1,
    "bi": 7
  },
  "Bandit Hatchet": {
    "b": 15,
    "bi": 176
  },
  "Crescent Quarterstaff": {
    "b": 25,
    "bi": 316
  },
  "Dyad Crossbow": {
    "b": 228,
    "bi": 794
  },
  "Elegant Glaive": {
    "b": 24,
    "bi": 303
  },
  "Emerald": {
    "b": 27,
    "bi": 875
  },
  "Golden Mantle": {
    "b": 51,
    "bi": 641
  },
  "Long Belt": {
    "b": 3,
    "bi": 29
  },
  "Maraketh Cuirass": {
    "b": 45,
    "bi": 503
  },
  "Moon Dagger": {
    "b": 12,
    "bi": 149
  },
  "Ruby": {
    "b": 26,
    "bi": 874
  },
  "Sapphire": {
    "b": 28,
    "bi": 876
  },
  "Twin Flail": {
    "b": 217,
    "bi": 766
  },
  "Charred Shortsword": {
    "b": 13,
    "bi": 163
  },
  "Effigial Tower Shield": {
    "b": 5,
    "bi": 52
  },
  "Ochre Sceptre": {
    "b": 17,
    "bi": 214
  },
  "War Spear": {
    "b": 216,
    "bi": 753
  },
  "Composite Bow": {
    "b": 20,
    "bi": 235
  },
  "Cultist Greathammer": {
    "b": 23,
    "bi": 278
  },
  "Frenzied Talisman": {
    "b": 244,
    "bi": 976
  },
  "Plated Claw": {
    "b": 11,
    "bi": 136
  },
  "Rhoahide Coat": {
    "b": 46,
    "bi": 527
  },
  "Ridged Buckler": {
    "b": 6,
    "bi": 74
  },
  "Rippled Greatsword": {
    "b": 22,
    "bi": 265
  },
  "Silk Robe": {
    "b": 47,
    "bi": 551
  },
  "Tonal Focus": {
    "b": 229,
    "bi": 819
  },
  "Warpick": {
    "b": 16,
    "bi": 189
  },
  "Giant Life Flask": {
    "b": 60,
    "bi": 860
  },
  "Giant Mana Flask": {
    "b": 61,
    "bi": 869
  },
  "Antidote Charm": {
    "b": 241,
    "bi": 884
  },
  "Two-Point Quiver": {
    "b": 4,
    "bi": 40
  },
  "Chiming Staff": {
    "b": 21,
    "bi": 257
  },
  "Galvanic Wand": {
    "b": 221,
    "bi": 780
  },
  "Plate Belt": {
    "b": 3,
    "bi": 30
  },
  "Stellar Amulet": {
    "b": 2,
    "bi": 22
  },
  "Alloy Crossbow": {
    "b": 228,
    "bi": 795
  },
  "Chain Tiara": {
    "b": 54,
    "bi": 685
  },
  "Cloaked Mail": {
    "b": 48,
    "bi": 574
  },
  "Cowled Helm": {
    "b": 55,
    "bi": 704
  },
  "Crescent Axe": {
    "b": 15,
    "bi": 177
  },
  "Crescent Targe": {
    "b": 8,
    "bi": 95
  },
  "Crystal Focus": {
    "b": 229,
    "bi": 820
  },
  "Emerald Ring": {
    "b": 1,
    "bi": 8
  },
  "Forked Spear": {
    "b": 216,
    "bi": 754
  },
  "Jewelled Gloves": {
    "b": 35,
    "bi": 370
  },
  "Plated Mace": {
    "b": 16,
    "bi": 190
  },
  "Shrine Sceptre": {
    "b": 17,
    "bi": 217
  },
  "Slender Flail": {
    "b": 217,
    "bi": 767
  },
  "Spiked Buckler": {
    "b": 6,
    "bi": 75
  },
  "Studded Vest": {
    "b": 46,
    "bi": 528
  },
  "Swathed Cap": {
    "b": 53,
    "bi": 666
  },
  "Bolstered Mitts": {
    "b": 33,
    "bi": 340
  },
  "Engraved Knife": {
    "b": 12,
    "bi": 150
  },
  "Savage Greataxe": {
    "b": 24,
    "bi": 304
  },
  "Silk Slippers": {
    "b": 41,
    "bi": 451
  },
  "Spired Greathelm": {
    "b": 52,
    "bi": 647
  },
  "Steel Plate": {
    "b": 45,
    "bi": 504
  },
  "Trimmed Greaves": {
    "b": 39,
    "bi": 421
  },
  "Arced Longsword": {
    "b": 22,
    "bi": 266
  },
  "Dualstring Bow": {
    "b": 20,
    "bi": 236
  },
  "Edged Claw": {
    "b": 11,
    "bi": 137
  },
  "Jingling Crest Shield": {
    "b": 9,
    "bi": 115
  },
  "Keth Raiment": {
    "b": 47,
    "bi": 552
  },
  "Martyr Crown": {
    "b": 56,
    "bi": 720
  },
  "Primal Talisman": {
    "b": 244,
    "bi": 977
  },
  "Rampart Tower Shield": {
    "b": 5,
    "bi": 53
  },
  "Sectioned Bracers": {
    "b": 34,
    "bi": 355
  },
  "Shaman Mantle": {
    "b": 49,
    "bi": 600
  },
  "Sickle Sword": {
    "b": 13,
    "bi": 164
  },
  "Steelpoint Quarterstaff": {
    "b": 25,
    "bi": 317
  },
  "Steeltoe Boots": {
    "b": 40,
    "bi": 436
  },
  "Temple Maul": {
    "b": 23,
    "bi": 279
  },
  "Veiled Mask": {
    "b": 57,
    "bi": 736
  },
  "Wayfarer Jacket": {
    "b": 50,
    "bi": 622
  },
  "Colossal Life Flask": {
    "b": 60,
    "bi": 861
  },
  "Colossal Mana Flask": {
    "b": 61,
    "bi": 870
  },
  "Solar Amulet": {
    "b": 2,
    "bi": 23
  },
  "Ornate Belt": {
    "b": 3,
    "bi": 31
  },
  "Dousing Charm": {
    "b": 241,
    "bi": 885
  },
  "Grounding Charm": {
    "b": 241,
    "bi": 886
  },
  "Pearl Ring": {
    "b": 1,
    "bi": 9
  },
  "Acrid Wand": {
    "b": 18,
    "bi": 227
  },
  "Anchorite Garb": {
    "b": 50,
    "bi": 623
  },
  "Arced Claw": {
    "b": 11,
    "bi": 138
  },
  "Barbed Spear": {
    "b": 216,
    "bi": 755
  },
  "Blunt Quiver": {
    "b": 4,
    "bi": 41
  },
  "Bombard Crossbow": {
    "b": 228,
    "bi": 796
  },
  "Brigand Mace": {
    "b": 16,
    "bi": 191
  },
  "Carving Hatchet": {
    "b": 15,
    "bi": 178
  },
  "Chiseled Targe": {
    "b": 8,
    "bi": 96
  },
  "Cultist Bow": {
    "b": 20,
    "bi": 237
  },
  "Devouring Sceptre": {
    "b": 17,
    "bi": 218
  },
  "Doubled Gauntlets": {
    "b": 36,
    "bi": 384
  },
  "Elite Greathelm": {
    "b": 52,
    "bi": 648
  },
  "Explorer Armour": {
    "b": 48,
    "bi": 575
  },
  "Falchion": {
    "b": 13,
    "bi": 165
  },
  "Feathered Sandals": {
    "b": 41,
    "bi": 452
  },
  "Feathered Tiara": {
    "b": 54,
    "bi": 686
  },
  "Full Plate": {
    "b": 45,
    "bi": 505
  },
  "Goldcast Cuffs": {
    "b": 37,
    "bi": 396
  },
  "Heavy Crown": {
    "b": 56,
    "bi": 721
  },
  "Heraldric Tower Shield": {
    "b": 5,
    "bi": 54
  },
  "Hunter Hood": {
    "b": 53,
    "bi": 667
  },
  "Hunting Shoes": {
    "b": 44,
    "bi": 489
  },
  "Intricate Gloves": {
    "b": 35,
    "bi": 371
  },
  "Ironclad Vestments": {
    "b": 49,
    "bi": 601
  },
  "Leaden Greathammer": {
    "b": 23,
    "bi": 280
  },
  "Lizardscale Boots": {
    "b": 40,
    "bi": 437
  },
  "Moulded Mitts": {
    "b": 33,
    "bi": 341
  },
  "Obsidian Dagger": {
    "b": 12,
    "bi": 151
  },
  "Pelt Leggings": {
    "b": 43,
    "bi": 477
  },
  "Rending Halberd": {
    "b": 24,
    "bi": 305
  },
  "Rending Staff": {
    "b": 226,
    "bi": 788
  },
  "Ringed Buckler": {
    "b": 6,
    "bi": 76
  },
  "Scout's Vest": {
    "b": 46,
    "bi": 529
  },
  "Sectarian Crest Shield": {
    "b": 9,
    "bi": 116
  },
  "Shielded Helm": {
    "b": 55,
    "bi": 705
  },
  "Slicing Quarterstaff": {
    "b": 25,
    "bi": 318
  },
  "Spined Bracers": {
    "b": 34,
    "bi": 356
  },
  "Spiral Wraps": {
    "b": 38,
    "bi": 408
  },
  "Stacked Sabatons": {
    "b": 42,
    "bi": 465
  },
  "Stone Flail": {
    "b": 217,
    "bi": 768
  },
  "Stone Greatsword": {
    "b": 22,
    "bi": 267
  },
  "Stone Greaves": {
    "b": 39,
    "bi": 422
  },
  "Tribal Mask": {
    "b": 57,
    "bi": 737
  },
  "Voodoo Focus": {
    "b": 229,
    "bi": 821
  },
  "Votive Raiment": {
    "b": 47,
    "bi": 553
  },
  "Rabid Talisman": {
    "b": 244,
    "bi": 978
  },
  "Gold Amulet": {
    "b": 2,
    "bi": 24
  },
  "Prismatic Ring": {
    "b": 1,
    "bi": 10
  },
  "Clasped Sceptre": {
    "b": 17,
    "bi": 219
  },
  "Construct Hammer": {
    "b": 16,
    "bi": 192
  },
  "Hooked Claw": {
    "b": 11,
    "bi": 139
  },
  "Obsidian Greatsword": {
    "b": 22,
    "bi": 268
  },
  "Omen Crest Shield": {
    "b": 9,
    "bi": 117
  },
  "Plumed Focus": {
    "b": 229,
    "bi": 822
  },
  "Sacrificial Mantle": {
    "b": 49,
    "bi": 602
  },
  "Serpentscale Coat": {
    "b": 46,
    "bi": 530
  },
  "Stone Tower Shield": {
    "b": 5,
    "bi": 55
  },
  "Warrior Greathelm": {
    "b": 52,
    "bi": 649
  },
  "Barrier Quarterstaff": {
    "b": 25,
    "bi": 319
  },
  "Feathered Targe": {
    "b": 8,
    "bi": 97
  },
  "Sacrificial Axe": {
    "b": 15,
    "bi": 179
  },
  "Scale Mail": {
    "b": 48,
    "bi": 576
  },
  "Vaal Cuirass": {
    "b": 45,
    "bi": 506
  },
  "Construct Crossbow": {
    "b": 228,
    "bi": 797
  },
  "Crumbling Maul": {
    "b": 23,
    "bi": 281
  },
  "Offering Wand": {
    "b": 219,
    "bi": 778
  },
  "Reaping Staff": {
    "b": 227,
    "bi": 789
  },
  "Ring Flail": {
    "b": 217,
    "bi": 769
  },
  "Viper Cap": {
    "b": 53,
    "bi": 668
  },
  "Bloodletting Dagger": {
    "b": 12,
    "bi": 152
  },
  "Edged Buckler": {
    "b": 6,
    "bi": 77
  },
  "Scalper's Jacket": {
    "b": 50,
    "bi": 624
  },
  "Toxic Quiver": {
    "b": 4,
    "bi": 42
  },
  "Zealot Bow": {
    "b": 20,
    "bi": 238
  },
  "Altar Robe": {
    "b": 47,
    "bi": 554
  },
  "Amethyst Charm": {
    "b": 241,
    "bi": 892
  },
  "Breach Ring": {
    "b": 1,
    "bi": 14
  },
  "Broad Spear": {
    "b": 216,
    "bi": 756
  },
  "Cleansing Charm": {
    "b": 241,
    "bi": 963
  },
  "Gargantuan Life Flask": {
    "b": 60,
    "bi": 862
  },
  "Gargantuan Mana Flask": {
    "b": 61,
    "bi": 871
  },
  "Gold Circlet": {
    "b": 54,
    "bi": 687
  },
  "Gold Ring": {
    "b": 1,
    "bi": 11
  },
  "Jagged Greataxe": {
    "b": 24,
    "bi": 306
  },
  "Mail Belt": {
    "b": 3,
    "bi": 32
  },
  "Treasured Blade": {
    "b": 13,
    "bi": 166
  },
  "Vicious Talisman": {
    "b": 244,
    "bi": 979
  },
  "Double Belt": {
    "b": 3,
    "bi": 33
  },
  "Serrated Quiver": {
    "b": 4,
    "bi": 43
  },
  "Unset Ring": {
    "b": 1,
    "bi": 12
  },
  "Adherent Leggings": {
    "b": 43,
    "bi": 481
  },
  "Aged Tower Shield": {
    "b": 5,
    "bi": 61
  },
  "Artillery Bow": {
    "b": 20,
    "bi": 239
  },
  "Avian Robe": {
    "b": 47,
    "bi": 562
  },
  "Bandage Wraps": {
    "b": 38,
    "bi": 412
  },
  "Barbarian Plate": {
    "b": 45,
    "bi": 514
  },
  "Blackfire Crossbow": {
    "b": 228,
    "bi": 798
  },
  "Boarding Hatchet": {
    "b": 15,
    "bi": 180
  },
  "Bound Boots": {
    "b": 40,
    "bi": 441
  },
  "Braided Cuffs": {
    "b": 37,
    "bi": 400
  },
  "Buckled Wraps": {
    "b": 38,
    "bi": 409
  },
  "Calescent Hammer": {
    "b": 16,
    "bi": 198
  },
  "Cleric Vestments": {
    "b": 49,
    "bi": 603
  },
  "Closed Helm": {
    "b": 55,
    "bi": 706
  },
  "Commander Greathelm": {
    "b": 52,
    "bi": 650
  },
  "Corroded Greathelm": {
    "b": 52,
    "bi": 655
  },
  "Corsair Cap": {
    "b": 53,
    "bi": 669
  },
  "Corsair Vest": {
    "b": 46,
    "bi": 531
  },
  "Covered Sabatons": {
    "b": 42,
    "bi": 466
  },
  "Crossblade Spear": {
    "b": 216,
    "bi": 757
  },
  "Crucible Tower Shield": {
    "b": 5,
    "bi": 56
  },
  "Cutlass": {
    "b": 13,
    "bi": 167
  },
  "Detailed Mitts": {
    "b": 33,
    "bi": 342
  },
  "Devotional Sceptre": {
    "b": 17,
    "bi": 220
  },
  "Domed Helm": {
    "b": 55,
    "bi": 709
  },
  "Druidic Circlet": {
    "b": 54,
    "bi": 693
  },
  "Elementalist Robe": {
    "b": 47,
    "bi": 555
  },
  "Fine Bracers": {
    "b": 34,
    "bi": 357
  },
  "Flared Boots": {
    "b": 40,
    "bi": 438
  },
  "Flax Sandals": {
    "b": 41,
    "bi": 453
  },
  "Frigid Wand": {
    "b": 222,
    "bi": 781
  },
  "Guarded Flail": {
    "b": 217,
    "bi": 770
  },
  "Hefty Quarterstaff": {
    "b": 25,
    "bi": 320
  },
  "Hunting Bracers": {
    "b": 34,
    "bi": 360
  },
  "Icicle Staff": {
    "b": 224,
    "bi": 785
  },
  "Ironmail Gauntlets": {
    "b": 36,
    "bi": 388
  },
  "Ironwood Targe": {
    "b": 8,
    "bi": 103
  },
  "Juggernaut Plate": {
    "b": 45,
    "bi": 507
  },
  "Keen Greatsword": {
    "b": 22,
    "bi": 269
  },
  "Knight Armour": {
    "b": 48,
    "bi": 577
  },
  "Laced Sandals": {
    "b": 41,
    "bi": 456
  },
  "Laminate Buckler": {
    "b": 6,
    "bi": 78
  },
  "Mail Breaker": {
    "b": 12,
    "bi": 153
  },
  "Mailed Crown": {
    "b": 56,
    "bi": 725
  },
  "Morning Star": {
    "b": 16,
    "bi": 193
  },
  "Oak Buckler": {
    "b": 6,
    "bi": 83
  },
  "Oak Mask": {
    "b": 57,
    "bi": 741
  },
  "Ominous Gloves": {
    "b": 35,
    "bi": 375
  },
  "Painted Crest Shield": {
    "b": 9,
    "bi": 123
  },
  "Patchwork Vest": {
    "b": 46,
    "bi": 538
  },
  "Pauascale Gloves": {
    "b": 35,
    "bi": 372
  },
  "Plate Gauntlets": {
    "b": 36,
    "bi": 385
  },
  "Plated Greaves": {
    "b": 39,
    "bi": 426
  },
  "Plated Mitts": {
    "b": 33,
    "bi": 345
  },
  "Pointed Maul": {
    "b": 23,
    "bi": 282
  },
  "Razorglass Claw": {
    "b": 11,
    "bi": 140
  },
  "Reaching Quarterstaff": {
    "b": 25,
    "bi": 325
  },
  "Reaver Glaive": {
    "b": 24,
    "bi": 307
  },
  "Reefsteel Greaves": {
    "b": 39,
    "bi": 423
  },
  "Ring Mail": {
    "b": 48,
    "bi": 586
  },
  "Rotted Hood": {
    "b": 53,
    "bi": 674
  },
  "Runed Focus": {
    "b": 229,
    "bi": 946
  },
  "Scoundrel Jacket": {
    "b": 50,
    "bi": 625
  },
  "Snakewood Greathammer": {
    "b": 23,
    "bi": 287
  },
  "Snakewood Shortbow": {
    "b": 20,
    "bi": 244
  },
  "Soldiering Sabatons": {
    "b": 42,
    "bi": 469
  },
  "Solid Mask": {
    "b": 57,
    "bi": 738
  },
  "Spiritbone Crown": {
    "b": 56,
    "bi": 722
  },
  "Steelhead Spear": {
    "b": 216,
    "bi": 902
  },
  "Steelpoint Shoes": {
    "b": 44,
    "bi": 490
  },
  "Taut Crossbow": {
    "b": 228,
    "bi": 803
  },
  "Templar Vestments": {
    "b": 49,
    "bi": 610
  },
  "Verisium Cuffs": {
    "b": 37,
    "bi": 934
  },
  "Vermeil Circlet": {
    "b": 54,
    "bi": 938
  },
  "Wayfarer Shoes": {
    "b": 44,
    "bi": 493
  },
  "Wayward Crest Shield": {
    "b": 9,
    "bi": 118
  },
  "Weaver Leggings": {
    "b": 43,
    "bi": 478
  },
  "Wreath Focus": {
    "b": 229,
    "bi": 828
  },
  "Stratified Targe": {
    "b": 8,
    "bi": 98
  },
  "Voltfang Talisman": {
    "b": 244,
    "bi": 980
  },
  "Icicle Flail": {
    "b": 217,
    "bi": 771
  },
  "Kalguuran Forgehammer": {
    "b": 16,
    "bi": 953
  },
  "Avian Tiara": {
    "b": 54,
    "bi": 694
  },
  "Bandit Mask": {
    "b": 57,
    "bi": 742
  },
  "Barbarous Quarterstaff": {
    "b": 25,
    "bi": 326
  },
  "Bearskin Mantle": {
    "b": 49,
    "bi": 611
  },
  "Blacksmith Maul": {
    "b": 23,
    "bi": 288
  },
  "Coursing Spear": {
    "b": 216,
    "bi": 903
  },
  "Cursespeaker's Robe": {
    "b": 47,
    "bi": 563
  },
  "Engraved Crest Shield": {
    "b": 9,
    "bi": 124
  },
  "Engraved Helm": {
    "b": 55,
    "bi": 710
  },
  "Flared Mace": {
    "b": 16,
    "bi": 199
  },
  "Forest Crown": {
    "b": 56,
    "bi": 726
  },
  "Fur-lined Targe": {
    "b": 8,
    "bi": 104
  },
  "Fury Cleaver": {
    "b": 15,
    "bi": 181
  },
  "Hunting Coat": {
    "b": 46,
    "bi": 539
  },
  "Mercenary Greathelm": {
    "b": 52,
    "bi": 656
  },
  "Metalworked Tower Shield": {
    "b": 5,
    "bi": 62
  },
  "Oiled Jacket": {
    "b": 50,
    "bi": 633
  },
  "Painted Buckler": {
    "b": 6,
    "bi": 84
  },
  "Protector Bow": {
    "b": 20,
    "bi": 245
  },
  "Robust Crossbow": {
    "b": 228,
    "bi": 804
  },
  "Rugged Cuirass": {
    "b": 45,
    "bi": 515
  },
  "Scoundrel Armour": {
    "b": 48,
    "bi": 587
  },
  "Staghorn Focus": {
    "b": 229,
    "bi": 829
  },
  "Wool Cap": {
    "b": 53,
    "bi": 675
  },
  "Ancient Greatblade": {
    "b": 22,
    "bi": 270
  },
  "Jade Club": {
    "b": 16,
    "bi": 194
  },
  "Kris Knife": {
    "b": 12,
    "bi": 154
  },
  "Mystic Raiment": {
    "b": 47,
    "bi": 556
  },
  "Roaring Staff": {
    "b": 21,
    "bi": 258
  },
  "Sharktooth Claw": {
    "b": 11,
    "bi": 141
  },
  "Smooth Quarterstaff": {
    "b": 25,
    "bi": 321
  },
  "Torture Wand": {
    "b": 18,
    "bi": 228
  },
  "Wrath Sceptre": {
    "b": 17,
    "bi": 221
  },
  "Ancestor Tower Shield": {
    "b": 5,
    "bi": 57
  },
  "Ancestral Mail": {
    "b": 48,
    "bi": 578
  },
  "Chieftain Cuirass": {
    "b": 45,
    "bi": 508
  },
  "Ember Greataxe": {
    "b": 24,
    "bi": 308
  },
  "Golden Charm": {
    "b": 241,
    "bi": 893
  },
  "Heavy Belt": {
    "b": 3,
    "bi": 34
  },
  "Jade Tiara": {
    "b": 54,
    "bi": 689
  },
  "Leatherbound Hood": {
    "b": 53,
    "bi": 670
  },
  "Pearl Buckler": {
    "b": 6,
    "bi": 79
  },
  "Piercing Crossbow": {
    "b": 228,
    "bi": 799
  },
  "Runic Shortsword": {
    "b": 13,
    "bi": 168
  },
  "Seer Crest Shield": {
    "b": 9,
    "bi": 119
  },
  "Totemic Greatclub": {
    "b": 23,
    "bi": 283
  },
  "Transcendent Life Flask": {
    "b": 60,
    "bi": 863
  },
  "Transcendent Mana Flask": {
    "b": 61,
    "bi": 872
  },
  "Tribal Bow": {
    "b": 20,
    "bi": 240
  },
  "Arcing Quarterstaff": {
    "b": 25,
    "bi": 327
  },
  "Ascetic Garb": {
    "b": 50,
    "bi": 626
  },
  "Bangled Sandals": {
    "b": 41,
    "bi": 457
  },
  "Battle Pick": {
    "b": 16,
    "bi": 200
  },
  "Bound Leggings": {
    "b": 43,
    "bi": 482
  },
  "Cambric Wraps": {
    "b": 38,
    "bi": 413
  },
  "Captain Gauntlets": {
    "b": 36,
    "bi": 389
  },
  "Carved Targe": {
    "b": 8,
    "bi": 99
  },
  "Chain Vestments": {
    "b": 49,
    "bi": 612
  },
  "Coiled Buckler": {
    "b": 6,
    "bi": 85
  },
  "Cultist Tower Shield": {
    "b": 5,
    "bi": 63
  },
  "Descry Crest Shield": {
    "b": 9,
    "bi": 125
  },
  "Desert Circlet": {
    "b": 54,
    "bi": 695
  },
  "Elegant Mitts": {
    "b": 33,
    "bi": 346
  },
  "Embellished Gloves": {
    "b": 35,
    "bi": 930
  },
  "Evangelist Garb": {
    "b": 50,
    "bi": 634
  },
  "Fierce Greathelm": {
    "b": 52,
    "bi": 651
  },
  "Goldwork Sabatons": {
    "b": 42,
    "bi": 470
  },
  "Heirloom Cuffs": {
    "b": 37,
    "bi": 401
  },
  "Homeguard Greathelm": {
    "b": 52,
    "bi": 657
  },
  "Jingling Focus": {
    "b": 229,
    "bi": 830
  },
  "Lionheart Greaves": {
    "b": 39,
    "bi": 427
  },
  "Luxurious Robe": {
    "b": 47,
    "bi": 564
  },
  "Mercenary Targe": {
    "b": 8,
    "bi": 105
  },
  "Narrow Hood": {
    "b": 53,
    "bi": 676
  },
  "Painted Crossbow": {
    "b": 228,
    "bi": 805
  },
  "Primed Quiver": {
    "b": 4,
    "bi": 44
  },
  "Rider Bow": {
    "b": 20,
    "bi": 246
  },
  "Riding Coat": {
    "b": 46,
    "bi": 540
  },
  "Sandsworn Cuirass": {
    "b": 45,
    "bi": 516
  },
  "Seaglass Spear": {
    "b": 216,
    "bi": 758
  },
  "Silverbuckled Shoes": {
    "b": 44,
    "bi": 494
  },
  "Skulking Mask": {
    "b": 57,
    "bi": 743
  },
  "Sleek Boots": {
    "b": 40,
    "bi": 442
  },
  "Smuggler Coat": {
    "b": 46,
    "bi": 532
  },
  "Soldier Helm": {
    "b": 55,
    "bi": 711
  },
  "Swift Bracers": {
    "b": 34,
    "bi": 361
  },
  "Swift Spear": {
    "b": 216,
    "bi": 904
  },
  "Tideseer Mantle": {
    "b": 49,
    "bi": 604
  },
  "Wanderer Armour": {
    "b": 48,
    "bi": 588
  },
  "Whorl Focus": {
    "b": 229,
    "bi": 947
  },
  "Zealot Crown": {
    "b": 56,
    "bi": 727
  },
  "Zealot Greathammer": {
    "b": 23,
    "bi": 289
  },
  "Anima Quarterstaff": {
    "b": 25,
    "bi": 322
  },
  "Armoured Claw": {
    "b": 11,
    "bi": 142
  },
  "Aromatic Sceptre": {
    "b": 17,
    "bi": 222
  },
  "Battle Axe": {
    "b": 15,
    "bi": 182
  },
  "Burnished Gauntlets": {
    "b": 36,
    "bi": 386
  },
  "Ceremonial Halberd": {
    "b": 24,
    "bi": 309
  },
  "Clandestine Jacket": {
    "b": 50,
    "bi": 627
  },
  "Colosseum Plate": {
    "b": 45,
    "bi": 509
  },
  "Critical Wand": {
    "b": 18,
    "bi": 229
  },
  "Cumbrous Crossbow": {
    "b": 228,
    "bi": 800
  },
  "Decorated Helm": {
    "b": 55,
    "bi": 707
  },
  "Elegant Focus": {
    "b": 229,
    "bi": 825
  },
  "Embroidered Gloves": {
    "b": 35,
    "bi": 373
  },
  "Flanged Greatblade": {
    "b": 22,
    "bi": 271
  },
  "Flexile Sabatons": {
    "b": 42,
    "bi": 467
  },
  "Furtive Wraps": {
    "b": 38,
    "bi": 410
  },
  "Gilded Vestments": {
    "b": 49,
    "bi": 605
  },
  "Gilt Leggings": {
    "b": 43,
    "bi": 479
  },
  "Greatbow": {
    "b": 20,
    "bi": 241
  },
  "Greatmace": {
    "b": 23,
    "bi": 284
  },
  "Hardened Bracers": {
    "b": 34,
    "bi": 358
  },
  "Imperial Robe": {
    "b": 47,
    "bi": 557
  },
  "Lamellar Mail": {
    "b": 48,
    "bi": 579
  },
  "Lavish Crown": {
    "b": 56,
    "bi": 723
  },
  "Leatherplate Boots": {
    "b": 40,
    "bi": 439
  },
  "Lumbering Talisman": {
    "b": 244,
    "bi": 981
  },
  "Lumen Mace": {
    "b": 16,
    "bi": 195
  },
  "Messer": {
    "b": 13,
    "bi": 169
  },
  "Monument Greaves": {
    "b": 39,
    "bi": 424
  },
  "Mosaic Targe": {
    "b": 8,
    "bi": 100
  },
  "Noble Circlet": {
    "b": 54,
    "bi": 690
  },
  "Ornate Buckler": {
    "b": 6,
    "bi": 80
  },
  "Paralysing Staff": {
    "b": 225,
    "bi": 787
  },
  "Parrying Dagger": {
    "b": 12,
    "bi": 155
  },
  "Phalanx Tower Shield": {
    "b": 5,
    "bi": 58
  },
  "Righteous Cuffs": {
    "b": 37,
    "bi": 398
  },
  "Sentinel Greathelm": {
    "b": 52,
    "bi": 652
  },
  "Shaded Mask": {
    "b": 57,
    "bi": 739
  },
  "Stoic Crest Shield": {
    "b": 9,
    "bi": 120
  },
  "Strider Vest": {
    "b": 46,
    "bi": 533
  },
  "Studded Sandals": {
    "b": 41,
    "bi": 454
  },
  "Sword Spear": {
    "b": 216,
    "bi": 759
  },
  "Tearing Flail": {
    "b": 217,
    "bi": 772
  },
  "Titan Mitts": {
    "b": 33,
    "bi": 343
  },
  "Velour Shoes": {
    "b": 44,
    "bi": 491
  },
  "Velvet Cap": {
    "b": 53,
    "bi": 671
  },
  "Ancient Mitts": {
    "b": 33,
    "bi": 347
  },
  "Arrayed Focus": {
    "b": 229,
    "bi": 831
  },
  "Baroque Gloves": {
    "b": 35,
    "bi": 377
  },
  "Branched Spear": {
    "b": 216,
    "bi": 905
  },
  "Bulwark Tower Shield": {
    "b": 5,
    "bi": 64
  },
  "Cabalist Helm": {
    "b": 55,
    "bi": 712
  },
  "Commander Sword": {
    "b": 13,
    "bi": 170
  },
  "Dekharan Crest Shield": {
    "b": 9,
    "bi": 126
  },
  "Elegant Greathelm": {
    "b": 52,
    "bi": 658
  },
  "Elegant Greaves": {
    "b": 39,
    "bi": 428
  },
  "Elegant Plate": {
    "b": 45,
    "bi": 517
  },
  "Elegant Slippers": {
    "b": 41,
    "bi": 458
  },
  "Hallowed Crown": {
    "b": 56,
    "bi": 728
  },
  "Itinerant Jacket": {
    "b": 50,
    "bi": 635
  },
  "Layered Vest": {
    "b": 46,
    "bi": 541
  },
  "Mantled Mail": {
    "b": 48,
    "bi": 589
  },
  "Marching Mace": {
    "b": 16,
    "bi": 201
  },
  "Occultist Mantle": {
    "b": 49,
    "bi": 613
  },
  "Pariah Mask": {
    "b": 57,
    "bi": 744
  },
  "Polished Targe": {
    "b": 8,
    "bi": 106
  },
  "Precise Greathammer": {
    "b": 23,
    "bi": 285
  },
  "Profane Cleaver": {
    "b": 15,
    "bi": 183
  },
  "Refined Bracers": {
    "b": 34,
    "bi": 362
  },
  "Regalia Longsword": {
    "b": 22,
    "bi": 272
  },
  "River Raiment": {
    "b": 47,
    "bi": 565
  },
  "Sandsworn Tiara": {
    "b": 54,
    "bi": 696
  },
  "Solemn Maul": {
    "b": 23,
    "bi": 290
  },
  "Spikeward Buckler": {
    "b": 6,
    "bi": 86
  },
  "Studded Boots": {
    "b": 40,
    "bi": 443
  },
  "Twin Bow": {
    "b": 20,
    "bi": 247
  },
  "Twin Crossbow": {
    "b": 228,
    "bi": 806
  },
  "Venerated Mantle": {
    "b": 49,
    "bi": 606
  },
  "Waxing Quarterstaff": {
    "b": 25,
    "bi": 328
  },
  "Wrapped Cap": {
    "b": 53,
    "bi": 677
  },
  "Array Buckler": {
    "b": 6,
    "bi": 81
  },
  "Execratus Hammer": {
    "b": 16,
    "bi": 196
  },
  "Howling Talisman": {
    "b": 244,
    "bi": 985
  },
  "Penetrating Quiver": {
    "b": 4,
    "bi": 45
  },
  "Piercing Claw": {
    "b": 11,
    "bi": 143
  },
  "Striking Spear": {
    "b": 216,
    "bi": 760
  },
  "Utility Belt": {
    "b": 3,
    "bi": 35
  },
  "Arcane Dirk": {
    "b": 12,
    "bi": 156
  },
  "Covert Hood": {
    "b": 53,
    "bi": 672
  },
  "Dedalian Crossbow": {
    "b": 228,
    "bi": 801
  },
  "Double Limb Bow": {
    "b": 20,
    "bi": 242
  },
  "Graceful Quarterstaff": {
    "b": 25,
    "bi": 323
  },
  "Hardleather Coat": {
    "b": 46,
    "bi": 534
  },
  "Monastic Garb": {
    "b": 50,
    "bi": 628
  },
  "Primordial Wand": {
    "b": 218,
    "bi": 776
  },
  "Sanctified Staff": {
    "b": 21,
    "bi": 958
  },
  "Attuned Focus": {
    "b": 229,
    "bi": 826
  },
  "Aureate Targe": {
    "b": 8,
    "bi": 101
  },
  "Empyreal Crest Shield": {
    "b": 9,
    "bi": 121
  },
  "Goliath Greathelm": {
    "b": 52,
    "bi": 653
  },
  "Monument Greataxe": {
    "b": 24,
    "bi": 310
  },
  "Champion Cuirass": {
    "b": 45,
    "bi": 510
  },
  "Defiant Tower Shield": {
    "b": 5,
    "bi": 59
  },
  "Gladiator Armour": {
    "b": 48,
    "bi": 580
  },
  "Great Flail": {
    "b": 217,
    "bi": 773
  },
  "Pious Sceptre": {
    "b": 17,
    "bi": 223
  },
  "Plated Raiment": {
    "b": 47,
    "bi": 558
  },
  "Roaring Talisman": {
    "b": 244,
    "bi": 982
  },
  "Twilight Tiara": {
    "b": 54,
    "bi": 691
  },
  "Waystone (Tier 1)": {
    "b": 233,
    "bi": 840
  },
  "Adherent Bow": {
    "b": 20,
    "bi": 248
  },
  "Adherent's Raiment": {
    "b": 47,
    "bi": 566
  },
  "Adorned Wraps": {
    "b": 38,
    "bi": 414
  },
  "Avian Mask": {
    "b": 57,
    "bi": 745
  },
  "Bandit Mace": {
    "b": 16,
    "bi": 202
  },
  "Bastion Sabatons": {
    "b": 42,
    "bi": 471
  },
  "Bladed Quarterstaff": {
    "b": 25,
    "bi": 329
  },
  "Cannonade Crossbow": {
    "b": 228,
    "bi": 807
  },
  "Carved Greaves": {
    "b": 39,
    "bi": 429
  },
  "Cultist Focus": {
    "b": 229,
    "bi": 832
  },
  "Deerstalker Hood": {
    "b": 53,
    "bi": 678
  },
  "Dunerunner Sandals": {
    "b": 41,
    "bi": 459
  },
  "Feathered Mitts": {
    "b": 33,
    "bi": 348
  },
  "Fury Talisman": {
    "b": 244,
    "bi": 986
  },
  "Gladiatoral Helm": {
    "b": 55,
    "bi": 713
  },
  "Gold Gloves": {
    "b": 35,
    "bi": 378
  },
  "Hatungo Garb": {
    "b": 50,
    "bi": 636
  },
  "Heavy Greathammer": {
    "b": 23,
    "bi": 291
  },
  "Heavy Plate": {
    "b": 45,
    "bi": 518
  },
  "Inquisitor Crown": {
    "b": 56,
    "bi": 729
  },
  "Jagged Spear": {
    "b": 216,
    "bi": 906
  },
  "Jingling Buckler": {
    "b": 6,
    "bi": 87
  },
  "Jungle Tiara": {
    "b": 54,
    "bi": 697
  },
  "Noble Greathelm": {
    "b": 52,
    "bi": 659
  },
  "Noble Tower Shield": {
    "b": 5,
    "bi": 65
  },
  "Ornate Cuffs": {
    "b": 37,
    "bi": 402
  },
  "Plated Vestments": {
    "b": 49,
    "bi": 614
  },
  "Quartered Crest Shield": {
    "b": 9,
    "bi": 127
  },
  "Runner Vest": {
    "b": 46,
    "bi": 542
  },
  "Serpentscale Boots": {
    "b": 40,
    "bi": 444
  },
  "Shamanistic Leggings": {
    "b": 43,
    "bi": 483
  },
  "Spiked Bracers": {
    "b": 34,
    "bi": 363
  },
  "Stone Targe": {
    "b": 8,
    "bi": 107
  },
  "Trailblazer Armour": {
    "b": 48,
    "bi": 590
  },
  "Treerunner Shoes": {
    "b": 44,
    "bi": 495
  },
  "Zealot Gauntlets": {
    "b": 36,
    "bi": 390
  },
  "Ultimate Life Flask": {
    "b": 60,
    "bi": 864
  },
  "Ultimate Mana Flask": {
    "b": 61,
    "bi": 873
  },
  "Bladeguard Buckler": {
    "b": 6,
    "bi": 88
  },
  "Goldworked Tower Shield": {
    "b": 5,
    "bi": 66
  },
  "Hallowed Focus": {
    "b": 229,
    "bi": 833
  },
  "Volant Quiver": {
    "b": 4,
    "bi": 46
  },
  "Avian Targe": {
    "b": 8,
    "bi": 108
  },
  "Bleak Crossbow": {
    "b": 228,
    "bi": 808
  },
  "Ceremonial Robe": {
    "b": 47,
    "bi": 567
  },
  "Disintegrating Maul": {
    "b": 23,
    "bi": 292
  },
  "Fine Belt": {
    "b": 3,
    "bi": 36
  },
  "Glowering Crest Shield": {
    "b": 9,
    "bi": 128
  },
  "Golden Mail": {
    "b": 48,
    "bi": 591
  },
  "Guardian Quarterstaff": {
    "b": 25,
    "bi": 330
  },
  "Hawker's Jacket": {
    "b": 50,
    "bi": 637
  },
  "Heartcarver Mantle": {
    "b": 49,
    "bi": 615
  },
  "Lizardscale Coat": {
    "b": 46,
    "bi": 543
  },
  "Massive Spear": {
    "b": 216,
    "bi": 907
  },
  "Militant Bow": {
    "b": 20,
    "bi": 249
  },
  "Stone Cuirass": {
    "b": 45,
    "bi": 519
  },
  "Structured Hammer": {
    "b": 16,
    "bi": 203
  },
  "Cruel Talisman": {
    "b": 244,
    "bi": 987
  },
  "Abyss Precursor Tablet": {
    "b": 243,
    "bi": 967
  },
  "Abyssal Flail": {
    "b": 217,
    "bi": 774
  },
  "Adorned Gloves": {
    "b": 35,
    "bi": 374
  },
  "Aegis Buckler": {
    "b": 6,
    "bi": 82
  },
  "Archon Crown": {
    "b": 56,
    "bi": 730
  },
  "Armoured Cap": {
    "b": 53,
    "bi": 673
  },
  "Blacksteel Tower Shield": {
    "b": 5,
    "bi": 60
  },
  "Bladed Shoes": {
    "b": 44,
    "bi": 492
  },
  "Bold Sabatons": {
    "b": 42,
    "bi": 468
  },
  "Bound Cuffs": {
    "b": 37,
    "bi": 403
  },
  "Bound Sandals": {
    "b": 41,
    "bi": 460
  },
  "Breach Precursor Tablet": {
    "b": 237,
    "bi": 877
  },
  "Brigand Mask": {
    "b": 57,
    "bi": 746
  },
  "Bulwark Greaves": {
    "b": 39,
    "bi": 430
  },
  "Cinched Boots": {
    "b": 40,
    "bi": 445
  },
  "Cinquedea": {
    "b": 12,
    "bi": 157
  },
  "Condemned Talisman": {
    "b": 244,
    "bi": 984
  },
  "Dark Blade": {
    "b": 13,
    "bi": 171
  },
  "Dark Staff": {
    "b": 21,
    "bi": 260
  },
  "Dastard Armour": {
    "b": 48,
    "bi": 592
  },
  "Death Mask": {
    "b": 57,
    "bi": 740
  },
  "Deified Crest Shield": {
    "b": 9,
    "bi": 122
  },
  "Delirium Precursor Tablet": {
    "b": 239,
    "bi": 879
  },
  "Dread Hatchet": {
    "b": 15,
    "bi": 184
  },
  "Druidic Crown": {
    "b": 56,
    "bi": 724
  },
  "Druidic Focus": {
    "b": 229,
    "bi": 834
  },
  "Dueling Wand": {
    "b": 18,
    "bi": 230
  },
  "Elaborate Sandals": {
    "b": 41,
    "bi": 455
  },
  "Embroidered Boots": {
    "b": 40,
    "bi": 440
  },
  "Engraved Bracers": {
    "b": 34,
    "bi": 359
  },
  "Esoteric Crossbow": {
    "b": 228,
    "bi": 802
  },
  "Expedition Precursor Tablet": {
    "b": 240,
    "bi": 878
  },
  "Exquisite Vest": {
    "b": 46,
    "bi": 535
  },
  "Faithful Leggings": {
    "b": 43,
    "bi": 484
  },
  "Gallant Helm": {
    "b": 55,
    "bi": 708
  },
  "Giant Maul": {
    "b": 23,
    "bi": 286
  },
  "Glorious Plate": {
    "b": 45,
    "bi": 511
  },
  "Grand Cuisses": {
    "b": 232,
    "bi": 839
  },
  "Grand Manchettes": {
    "b": 231,
    "bi": 838
  },
  "Grand Mitts": {
    "b": 33,
    "bi": 344
  },
  "Grand Regalia": {
    "b": 51,
    "bi": 643
  },
  "Grand Targe": {
    "b": 8,
    "bi": 102
  },
  "Grand Visage": {
    "b": 230,
    "bi": 837
  },
  "Grim Gloves": {
    "b": 35,
    "bi": 379
  },
  "Guardian Greathelm": {
    "b": 52,
    "bi": 654
  },
  "Hallowed Sceptre": {
    "b": 17,
    "bi": 224
  },
  "Havoc Raiment": {
    "b": 47,
    "bi": 559
  },
  "Heavy Bow": {
    "b": 20,
    "bi": 243
  },
  "Helix Spear": {
    "b": 216,
    "bi": 761
  },
  "Heroic Armour": {
    "b": 48,
    "bi": 581
  },
  "Intricate Crest Shield": {
    "b": 9,
    "bi": 129
  },
  "Knightly Mitts": {
    "b": 33,
    "bi": 349
  },
  "Magus Focus": {
    "b": 229,
    "bi": 827
  },
  "Magus Tiara": {
    "b": 54,
    "bi": 692
  },
  "Mammoth Targe": {
    "b": 8,
    "bi": 109
  },
  "Ornate Gauntlets": {
    "b": 36,
    "bi": 387
  },
  "Overseer Precursor Tablet": {
    "b": 242,
    "bi": 914
  },
  "Pious Leggings": {
    "b": 43,
    "bi": 480
  },
  "Precursor Tablet": {
    "b": 236,
    "bi": 881
  },
  "Ravenous Staff": {
    "b": 21,
    "bi": 959
  },
  "Revered Vestments": {
    "b": 49,
    "bi": 607
  },
  "Ritual Precursor Tablet": {
    "b": 238,
    "bi": 880
  },
  "Royal Tower Shield": {
    "b": 5,
    "bi": 67
  },
  "Sacrificial Regalia": {
    "b": 51,
    "bi": 964
  },
  "Signet Cuffs": {
    "b": 37,
    "bi": 399
  },
  "Skycrown Tiara": {
    "b": 54,
    "bi": 698
  },
  "Sleek Jacket": {
    "b": 50,
    "bi": 638
  },
  "Soldier Cuirass": {
    "b": 45,
    "bi": 520
  },
  "Stalking Bracers": {
    "b": 34,
    "bi": 364
  },
  "Steelmail Gauntlets": {
    "b": 36,
    "bi": 391
  },
  "Swiftstalker Coat": {
    "b": 46,
    "bi": 544
  },
  "Talon Claw": {
    "b": 11,
    "bi": 144
  },
  "Torment Club": {
    "b": 16,
    "bi": 197
  },
  "Torment Jacket": {
    "b": 50,
    "bi": 629
  },
  "Totemic Greaves": {
    "b": 39,
    "bi": 425
  },
  "Ultra Greatsword": {
    "b": 22,
    "bi": 273
  },
  "Utility Wraps": {
    "b": 38,
    "bi": 411
  },
  "Veteran Sabatons": {
    "b": 42,
    "bi": 472
  },
  "Vile Greataxe": {
    "b": 24,
    "bi": 311
  },
  "Vile Robe": {
    "b": 47,
    "bi": 568
  },
  "Visceral Quiver": {
    "b": 4,
    "bi": 47
  },
  "Wanderer Shoes": {
    "b": 44,
    "bi": 496
  },
  "War Wraps": {
    "b": 38,
    "bi": 415
  },
  "Warded Helm": {
    "b": 55,
    "bi": 714
  },
  "Warmonger Greathelm": {
    "b": 52,
    "bi": 660
  },
  "Wingbeat Talisman": {
    "b": 244,
    "bi": 983
  },
  "Wolfskin Mantle": {
    "b": 49,
    "bi": 616
  },
  "Woven Cap": {
    "b": 53,
    "bi": 679
  },
  "Wyrm Quarterstaff": {
    "b": 25,
    "bi": 324
  },
  "Waystone (Tier 2)": {
    "b": 233,
    "bi": 841
  },
  "Anvil Maul": {
    "b": 23,
    "bi": 293
  },
  "Flanged Mace": {
    "b": 16,
    "bi": 204
  },
  "Ironwood Shortbow": {
    "b": 20,
    "bi": 250
  },
  "Orichalcum Spear": {
    "b": 216,
    "bi": 908
  },
  "Sinister Quarterstaff": {
    "b": 25,
    "bi": 331
  },
  "Spiny Talisman": {
    "b": 244,
    "bi": 988
  },
  "Stout Crossbow": {
    "b": 228,
    "bi": 809
  },
  "Waystone (Tier 3)": {
    "b": 233,
    "bi": 842
  },
  "Conqueror Plate": {
    "b": 45,
    "bi": 512
  },
  "Corvus Mantle": {
    "b": 49,
    "bi": 608
  },
  "Devout Garb": {
    "b": 50,
    "bi": 630
  },
  "Enlightened Robe": {
    "b": 47,
    "bi": 560
  },
  "Mail Coat": {
    "b": 46,
    "bi": 536
  },
  "Tournament Mail": {
    "b": 48,
    "bi": 584
  },
  "Waystone (Tier 4)": {
    "b": 233,
    "bi": 843
  },
  "Waystone (Tier 5)": {
    "b": 233,
    "bi": 844
  },
  "Ancient Cuffs": {
    "b": 37,
    "bi": 404
  },
  "Apostle Leggings": {
    "b": 43,
    "bi": 485
  },
  "Baroque Targe": {
    "b": 8,
    "bi": 110
  },
  "Cavalry Boots": {
    "b": 40,
    "bi": 446
  },
  "Charmed Shoes": {
    "b": 44,
    "bi": 497
  },
  "Commander Gauntlets": {
    "b": 36,
    "bi": 392
  },
  "Conjurer Mantle": {
    "b": 49,
    "bi": 617
  },
  "Cryptic Helm": {
    "b": 55,
    "bi": 715
  },
  "Desert Cap": {
    "b": 53,
    "bi": 680
  },
  "Elegant Wraps": {
    "b": 38,
    "bi": 416
  },
  "Faridun Mask": {
    "b": 57,
    "bi": 747
  },
  "Flowing Raiment": {
    "b": 47,
    "bi": 569
  },
  "Fortress Tower Shield": {
    "b": 5,
    "bi": 68
  },
  "Grand Bracers": {
    "b": 34,
    "bi": 365
  },
  "Gutspike Buckler": {
    "b": 6,
    "bi": 90
  },
  "Leyline Focus": {
    "b": 229,
    "bi": 835
  },
  "Luxurious Slippers": {
    "b": 41,
    "bi": 461
  },
  "Masked Greathelm": {
    "b": 52,
    "bi": 661
  },
  "Noble Sabatons": {
    "b": 42,
    "bi": 473
  },
  "Opulent Gloves": {
    "b": 35,
    "bi": 380
  },
  "Ornate Greaves": {
    "b": 39,
    "bi": 431
  },
  "Ornate Mitts": {
    "b": 33,
    "bi": 350
  },
  "Ornate Plate": {
    "b": 45,
    "bi": 521
  },
  "Rambler Jacket": {
    "b": 50,
    "bi": 639
  },
  "Reflecting Staff": {
    "b": 21,
    "bi": 968
  },
  "Saintly Crown": {
    "b": 56,
    "bi": 731
  },
  "Sekheman Crest Shield": {
    "b": 9,
    "bi": 130
  },
  "Shrouded Mail": {
    "b": 48,
    "bi": 595
  },
  "Slipstrike Vest": {
    "b": 46,
    "bi": 545
  },
  "Soaring Spear": {
    "b": 216,
    "bi": 965
  },
  "Sorcerous Tiara": {
    "b": 54,
    "bi": 699
  },
  "Waystone (Tier 6)": {
    "b": 234,
    "bi": 845
  },
  "Wildwood Talisman": {
    "b": 244,
    "bi": 994
  },
  "Waystone (Tier 7)": {
    "b": 234,
    "bi": 846
  },
  "Ashbark Talisman": {
    "b": 244,
    "bi": 989
  },
  "Cavalry Bow": {
    "b": 20,
    "bi": 251
  },
  "Crown Mace": {
    "b": 16,
    "bi": 205
  },
  "Engraved Crossbow": {
    "b": 228,
    "bi": 810
  },
  "Lunar Quarterstaff": {
    "b": 25,
    "bi": 332
  },
  "Pronged Spear": {
    "b": 216,
    "bi": 909
  },
  "Sacred Maul": {
    "b": 23,
    "bi": 294
  },
  "Waystone (Tier 8)": {
    "b": 234,
    "bi": 847
  },
  "Abyssal Cuirass": {
    "b": 45,
    "bi": 513
  },
  "Arcane Raiment": {
    "b": 47,
    "bi": 917
  },
  "Armoured Vest": {
    "b": 46,
    "bi": 537
  },
  "Assassin Garb": {
    "b": 50,
    "bi": 631
  },
  "Slayer Armour": {
    "b": 48,
    "bi": 585
  },
  "Waystone (Tier 9)": {
    "b": 234,
    "bi": 848
  },
  "Zenith Vestments": {
    "b": 49,
    "bi": 609
  },
  "Waystone (Tier 10)": {
    "b": 234,
    "bi": 849
  },
  "Alpha Talisman": {
    "b": 244,
    "bi": 992
  },
  "Ancient Buckler": {
    "b": 6,
    "bi": 91
  },
  "Barbed Bracers": {
    "b": 34,
    "bi": 366
  },
  "Champion Helm": {
    "b": 55,
    "bi": 716
  },
  "Cultist Gauntlets": {
    "b": 36,
    "bi": 393
  },
  "Death Mail": {
    "b": 48,
    "bi": 596
  },
  "Death Mantle": {
    "b": 49,
    "bi": 618
  },
  "Divine Crown": {
    "b": 56,
    "bi": 732
  },
  "Dragonscale Boots": {
    "b": 40,
    "bi": 447
  },
  "Falconer's Jacket": {
    "b": 50,
    "bi": 640
  },
  "Fortress Sabatons": {
    "b": 42,
    "bi": 474
  },
  "Gleaming Cuffs": {
    "b": 37,
    "bi": 405
  },
  "Guardian Spear": {
    "b": 216,
    "bi": 966
  },
  "Kamasan Tiara": {
    "b": 54,
    "bi": 700
  },
  "Paragon Greathelm": {
    "b": 52,
    "bi": 662
  },
  "Permafrost Staff": {
    "b": 21,
    "bi": 960
  },
  "Quickslip Shoes": {
    "b": 44,
    "bi": 498
  },
  "Sacramental Robe": {
    "b": 47,
    "bi": 570
  },
  "Sacred Focus": {
    "b": 229,
    "bi": 836
  },
  "Sandsworn Sandals": {
    "b": 41,
    "bi": 462
  },
  "Skullcrusher Quarterstaff": {
    "b": 25,
    "bi": 969
  },
  "Soaring Mask": {
    "b": 57,
    "bi": 748
  },
  "Soaring Targe": {
    "b": 8,
    "bi": 111
  },
  "Trapper Hood": {
    "b": 53,
    "bi": 681
  },
  "Utzaal Cuirass": {
    "b": 45,
    "bi": 522
  },
  "Vaal Crest Shield": {
    "b": 9,
    "bi": 131
  },
  "Vaal Gloves": {
    "b": 35,
    "bi": 381
  },
  "Vaal Greaves": {
    "b": 39,
    "bi": 432
  },
  "Vaal Mitts": {
    "b": 33,
    "bi": 351
  },
  "Vaal Tower Shield": {
    "b": 5,
    "bi": 69
  },
  "Vaal Wraps": {
    "b": 38,
    "bi": 417
  },
  "Warlock Leggings": {
    "b": 43,
    "bi": 486
  },
  "Waystone (Tier 11)": {
    "b": 235,
    "bi": 850
  },
  "Wyrmscale Coat": {
    "b": 46,
    "bi": 546
  },
  "Waystone (Tier 12)": {
    "b": 235,
    "bi": 851
  },
  "Desolate Crossbow": {
    "b": 228,
    "bi": 814
  },
  "Fang Talisman": {
    "b": 244,
    "bi": 990
  },
  "Flexed Crossbow": {
    "b": 228,
    "bi": 811
  },
  "Guardian Bow": {
    "b": 20,
    "bi": 252
  },
  "Ironwood Greathammer": {
    "b": 23,
    "bi": 295
  },
  "Marauding Mace": {
    "b": 16,
    "bi": 209
  },
  "Massive Greathammer": {
    "b": 23,
    "bi": 298
  },
  "Molten Hammer": {
    "b": 16,
    "bi": 206
  },
  "Razor Quarterstaff": {
    "b": 25,
    "bi": 336
  },
  "Spiked Spear": {
    "b": 216,
    "bi": 913
  },
  "Stalking Spear": {
    "b": 216,
    "bi": 910
  },
  "Striking Quarterstaff": {
    "b": 25,
    "bi": 333
  },
  "Thunder Talisman": {
    "b": 244,
    "bi": 995
  },
  "Warmonger Bow": {
    "b": 20,
    "bi": 255
  },
  "Waystone (Tier 13)": {
    "b": 235,
    "bi": 852
  },
  "Akoyan Club": {
    "b": 16,
    "bi": 954
  },
  "Akoyan Spear": {
    "b": 216,
    "bi": 955
  },
  "Bolting Quarterstaff": {
    "b": 25,
    "bi": 334
  },
  "Dreaming Quarterstaff": {
    "b": 25,
    "bi": 962
  },
  "Elegant Crossbow": {
    "b": 228,
    "bi": 957
  },
  "Fanatic Greathammer": {
    "b": 23,
    "bi": 296
  },
  "Flying Spear": {
    "b": 216,
    "bi": 911
  },
  "Fungal Talisman": {
    "b": 244,
    "bi": 991
  },
  "Gemini Bow": {
    "b": 20,
    "bi": 253
  },
  "Gemini Crossbow": {
    "b": 228,
    "bi": 812
  },
  "Jade Talisman": {
    "b": 244,
    "bi": 996
  },
  "Obliterator Bow": {
    "b": 20,
    "bi": 956
  },
  "Strife Pick": {
    "b": 16,
    "bi": 207
  },
  "Tawhoan Greatclub": {
    "b": 23,
    "bi": 961
  },
  "Waystone (Tier 14)": {
    "b": 235,
    "bi": 853
  },
  "Aegis Quarterstaff": {
    "b": 25,
    "bi": 335
  },
  "Fanatic Bow": {
    "b": 20,
    "bi": 254
  },
  "Fortified Hammer": {
    "b": 16,
    "bi": 208
  },
  "Grand Spear": {
    "b": 216,
    "bi": 912
  },
  "Maji Talisman": {
    "b": 244,
    "bi": 993
  },
  "Ruination Maul": {
    "b": 23,
    "bi": 297
  },
  "Siege Crossbow": {
    "b": 228,
    "bi": 813
  },
  "Waystone (Tier 15)": {
    "b": 235,
    "bi": 854
  },
  "Adherent Cuffs": {
    "b": 37,
    "bi": 935
  },
  "Ancestral Tiara": {
    "b": 54,
    "bi": 939
  },
  "Austere Garb": {
    "b": 50,
    "bi": 916
  },
  "Blacksteel Crest Shield": {
    "b": 9,
    "bi": 952
  },
  "Blacksteel Gauntlets": {
    "b": 36,
    "bi": 933
  },
  "Blacksteel Sabatons": {
    "b": 42,
    "bi": 926
  },
  "Corsair Coat": {
    "b": 46,
    "bi": 915
  },
  "Cryptic Crown": {
    "b": 56,
    "bi": 942
  },
  "Cryptic Leggings": {
    "b": 43,
    "bi": 927
  },
  "Daggerfoot Shoes": {
    "b": 44,
    "bi": 923
  },
  "Desert Buckler": {
    "b": 6,
    "bi": 949
  },
  "Drakeskin Boots": {
    "b": 40,
    "bi": 922
  },
  "Feathered Raiment": {
    "b": 47,
    "bi": 918
  },
  "Freebooter Cap": {
    "b": 53,
    "bi": 936
  },
  "Gladiatorial Helm": {
    "b": 55,
    "bi": 941
  },
  "Golden Targe": {
    "b": 8,
    "bi": 951
  },
  "Grinning Mask": {
    "b": 57,
    "bi": 937
  },
  "Imperial Greathelm": {
    "b": 52,
    "bi": 940
  },
  "Massive Mitts": {
    "b": 33,
    "bi": 932
  },
  "Polished Bracers": {
    "b": 34,
    "bi": 928
  },
  "Seastorm Mantle": {
    "b": 49,
    "bi": 921
  },
  "Secured Wraps": {
    "b": 38,
    "bi": 929
  },
  "Sekhema Sandals": {
    "b": 41,
    "bi": 924
  },
  "Sirenscale Gloves": {
    "b": 35,
    "bi": 931
  },
  "Tasalian Focus": {
    "b": 229,
    "bi": 948
  },
  "Tasalian Greaves": {
    "b": 39,
    "bi": 925
  },
  "Tawhoan Tower Shield": {
    "b": 5,
    "bi": 950
  },
  "Thane Mail": {
    "b": 48,
    "bi": 920
  },
  "Warlord Cuirass": {
    "b": 45,
    "bi": 919
  },
  "Waystone (Tier 16)": {
    "b": 235,
    "bi": 855
  }
};

/** id_essence for a Craft of Exile essence. Keyed by full name AND by stripped suffix,
 *  so both "Essence of Abrasion" and "Abrasion" resolve to the same id. */
export const COE_ESSENCES: Record<string, number> = {
  "Essence of Abrasion": 3326,
  "Abrasion": 3326,
  "Essence of Alacrity": 3381,
  "Alacrity": 3381,
  "Essence of Battle": 3331,
  "Battle": 3331,
  "Essence of Command": 3389,
  "Command": 3389,
  "Essence of Delirium": 3360,
  "Delirium": 3360,
  "Essence of Electricity": 3329,
  "Electricity": 3329,
  "Essence of Enhancement": 3325,
  "Enhancement": 3325,
  "Essence of Flames": 3327,
  "Flames": 3327,
  "Essence of Grounding": 3377,
  "Grounding": 3377,
  "Essence of Haste": 3333,
  "Haste": 3333,
  "Essence of Horror": 3361,
  "Horror": 3361,
  "Essence of Hysteria": 3359,
  "Hysteria": 3359,
  "Essence of Ice": 3328,
  "Ice": 3328,
  "Essence of Insanity": 3362,
  "Insanity": 3362,
  "Essence of Insulation": 3369,
  "Insulation": 3369,
  "Essence of Opulence": 3385,
  "Opulence": 3385,
  "Essence of Ruin": 3330,
  "Ruin": 3330,
  "Essence of Seeking": 3364,
  "Seeking": 3364,
  "Essence of Sorcery": 3332,
  "Sorcery": 3332,
  "Essence of Thawing": 3373,
  "Thawing": 3373,
  "Essence of the Abyss": 3367,
  "the Abyss": 3367,
  "Essence of the Body": 3323,
  "the Body": 3323,
  "Essence of the Infinite": 3334,
  "the Infinite": 3334,
  "Essence of the Mind": 3324,
  "the Mind": 3324,
  "Greater Essence of Abrasion": 3338,
  "Greater Essence of Alacrity": 3382,
  "Greater Essence of Battle": 3343,
  "Greater Essence of Command": 3390,
  "Greater Essence of Electricity": 3341,
  "Greater Essence of Enhancement": 3337,
  "Greater Essence of Flames": 3339,
  "Greater Essence of Grounding": 3378,
  "Greater Essence of Haste": 3345,
  "Greater Essence of Ice": 3340,
  "Greater Essence of Insulation": 3370,
  "Greater Essence of Opulence": 3386,
  "Greater Essence of Ruin": 3342,
  "Greater Essence of Seeking": 3365,
  "Greater Essence of Sorcery": 3344,
  "Greater Essence of Thawing": 3374,
  "Greater Essence of the Body": 3335,
  "Greater Essence of the Infinite": 3346,
  "Greater Essence of the Mind": 3336,
  "Lesser Essence of Abrasion": 3314,
  "Lesser Essence of Alacrity": 3380,
  "Lesser Essence of Battle": 3319,
  "Lesser Essence of Command": 3388,
  "Lesser Essence of Electricity": 3317,
  "Lesser Essence of Enhancement": 3313,
  "Lesser Essence of Flames": 3315,
  "Lesser Essence of Grounding": 3376,
  "Lesser Essence of Haste": 3321,
  "Lesser Essence of Ice": 3316,
  "Lesser Essence of Insulation": 3368,
  "Lesser Essence of Opulence": 3384,
  "Lesser Essence of Ruin": 3318,
  "Lesser Essence of Seeking": 3363,
  "Lesser Essence of Sorcery": 3320,
  "Lesser Essence of Thawing": 3372,
  "Lesser Essence of the Body": 3311,
  "Lesser Essence of the Infinite": 3322,
  "Lesser Essence of the Mind": 3312,
  "Perfect Essence of Abrasion": 3350,
  "Perfect Essence of Alacrity": 3383,
  "Perfect Essence of Battle": 3355,
  "Perfect Essence of Command": 3391,
  "Perfect Essence of Electricity": 3353,
  "Perfect Essence of Enhancement": 3349,
  "Perfect Essence of Flames": 3351,
  "Perfect Essence of Grounding": 3379,
  "Perfect Essence of Haste": 3357,
  "Perfect Essence of Ice": 3352,
  "Perfect Essence of Insulation": 3371,
  "Perfect Essence of Opulence": 3387,
  "Perfect Essence of Ruin": 3354,
  "Perfect Essence of Seeking": 3366,
  "Perfect Essence of Sorcery": 3356,
  "Perfect Essence of Thawing": 3375,
  "Perfect Essence of the Body": 3347,
  "Perfect Essence of the Infinite": 3358,
  "Perfect Essence of the Mind": 3348
};

/** Look up the CoE base IDs for a given base name. Tries the specific-item lookup
 *  first (more precise), then falls back to the category lookup. Returns null if neither. */
export function lookupCoeBase(name: string): { b: number; bi?: number } | null {
  if (COE_BITEMS[name]) return COE_BITEMS[name];
  if (COE_BASE_CATEGORIES[name]) return COE_BASE_CATEGORIES[name];
  return null;
}

/** Look up the CoE essence ID for a name like "Essence of Abrasion" or "Abrasion"
 *  or "Greater Essence of Abrasion" (we strip the tier prefix). */
export function lookupCoeEssence(name: string): number | null {
  if (!name) return null;
  // Strip tier prefixes like "Greater ", "Perfect ", "Lesser ", "Normal "
  const stripped = name.replace(/^(Greater|Perfect|Lesser|Normal)s+/i, "");
  return COE_ESSENCES[stripped] ?? COE_ESSENCES[name] ?? null;
}
