import { MOD_DATA } from "@/lib/mod-weights";

/**
 * Build a compact markdown section listing every authoritative PoE2 mod name
 * grouped by base category × prefix/suffix. Injected into the Oracle's system
 * prompt so the recipe block's targetAffixes use names that resolve in our
 * CoE URL builder.
 *
 * Without this, the Oracle paraphrases ("+# to maximum Energy Shield" instead
 * of "#% increased Energy Shield") and the &req= URL parameter can't be built
 * — meaning users have to manually click affixes in CoE after using the Verify
 * button. Same fix pattern as the bases injection (src/lib/bases-prompt.ts);
 * same problem one layer deeper.
 *
 * Source: the community-maintained PoE2 mod-weights spreadsheet
 * (the same one Craft of Exile uses). Regenerated by
 * scripts/build-mod-weights.mjs.
 */
export function buildModsPromptSection(): string {
  const bases = Object.keys(MOD_DATA).sort();
  let totalMods = 0;
  let body = "";

  for (const base of bases) {
    const prefixes = Object.keys(MOD_DATA[base].PREFIX ?? {}).sort();
    const suffixes = Object.keys(MOD_DATA[base].SUFFIX ?? {}).sort();
    if (prefixes.length === 0 && suffixes.length === 0) continue;
    totalMods += prefixes.length + suffixes.length;
    body += `### ${base}\n`;
    if (prefixes.length) body += `**Prefixes (${prefixes.length}):** ${prefixes.join(", ")}\n`;
    if (suffixes.length) body += `**Suffixes (${suffixes.length}):** ${suffixes.join(", ")}\n`;
    body += "\n";
  }

  return `## Authoritative PoE2 Mod Names — use ONLY these in recipe targetAffixes

When you populate a recipe block's \`targetAffixes\` array, the \`name\` field of each affix MUST be selected verbatim from the list below. These are the canonical mod names from the community-maintained PoE2 mod-weights spreadsheet (the same data Craft of Exile uses). The app looks them up to build CoE's \`req=\` URL parameter — every paraphrase costs one manual click for the user in CoE.

**DO NOT paraphrase mod names.** Common failure modes to avoid:
- ❌ \`"% Phys Damage"\` → ✅ \`"#% increased Physical Damage"\`
- ❌ \`"Flat Phys"\` → ✅ \`"Adds # to # Physical Damage"\`
- ❌ \`"+# to maximum Energy Shield"\` → ✅ \`"#% increased Energy Shield"\` or \`"# to maximum Energy Shield"\` (use exactly what's listed below)
- ❌ \`"Crit Multi"\` → ✅ \`"+#% to Critical Damage Bonus"\`
- ❌ \`"Fire Res"\` → ✅ \`"#% to Fire Resistance"\` (exact phrasing — note no "+" prefix in canonical form)

\`#\` is a literal placeholder for numeric ranges — do NOT substitute actual numbers in the recipe block. The lookup is by mod template, not specific roll.

If a mod you want isn't on the list, pick the closest valid mod and substitute. NEVER fabricate a mod name.

There are ${totalMods} mods across ${bases.length} base categories. The mods you write in the recipe block MUST be valid for the base you chose — i.e. if recipe.base resolves to category "Body Armour (INT)", pick mods from that section below.

${body.trim()}
`;
}
