import { COE_BASE_MODS } from "@/lib/coe-lookup";

/**
 * Build a compact markdown section listing every authoritative PoE2 mod name
 * grouped by base category × prefix/suffix. Injected into the Oracle's system
 * prompt so the recipe block's targetAffixes use names that resolve in our
 * CoE URL builder AND match what actually rolls on each base.
 *
 * Source: CoE's basemods table from their public poec_data.json — this is the
 * same mod pool CoE's emulator displays for each base. Authoritative and
 * more complete than the Google Sheet (CoE has mods the sheet misses).
 *
 * Regenerated by scripts/build-coe-lookup.mjs whenever the upstream changes.
 */
export function buildModsPromptSection(): string {
  const cats = Object.keys(COE_BASE_MODS).sort();
  let totalMods = 0;
  let body = "";

  for (const cat of cats) {
    const pool = COE_BASE_MODS[cat];
    if (!pool.prefixes.length && !pool.suffixes.length) continue;
    totalMods += pool.prefixes.length + pool.suffixes.length;
    body += `### ${cat}\n`;
    if (pool.prefixes.length) body += `**Prefixes (${pool.prefixes.length}):** ${pool.prefixes.join(", ")}\n`;
    if (pool.suffixes.length) body += `**Suffixes (${pool.suffixes.length}):** ${pool.suffixes.join(", ")}\n`;
    body += "\n";
  }

  return `## Authoritative PoE2 Mod Pools — per base category

Below is every prefix and suffix that legally rolls on each PoE2 base category, sourced from Craft of Exile's own data (the same pool CoE's emulator shows). When you populate a recipe block's \`targetAffixes\` array, the \`name\` field of each affix MUST be a verbatim copy of a name in the relevant category below — AND it must be in the correct affix slot (prefixes go in \`prefixes\`, suffixes in \`suffixes\`).

The recipe validator runs every response through this exact lookup. Any mod you put in the wrong category, the wrong slot, or with paraphrased wording will surface a warning banner to the user above your response — so be precise.

**DO NOT paraphrase mod names.** Common failure modes:
- ❌ \`"% Phys Damage"\` → ✅ \`"#% increased Physical Damage"\`
- ❌ \`"Flat Phys"\` → ✅ \`"Adds # to # Physical Damage"\`
- ❌ \`"+# to maximum Energy Shield"\` → ✅ use the exact phrasing from the base's prefix list below (some bases have "# to maximum Energy Shield", others "#% increased Energy Shield")
- ❌ \`"Crit Multi"\` → ✅ \`"+#% to Critical Damage Bonus"\`
- ❌ \`"Fire Res"\` → ✅ \`"#% to Fire Resistance"\` (no "+" prefix in canonical form)

**CRITICAL — Weapon vs Quiver damage-mod naming differs:**
- On **weapons** (Bow, Crossbow, Wand, Staff, Sceptre, all melee weapons): canonical name is \`"Adds # to # X Damage"\` (NO "to Attacks" suffix). The weapon itself deals the damage.
- On **Quivers** (and some off-hands): canonical name is \`"Adds # to # X damage to Attacks"\` (WITH "to Attacks" suffix). The quiver doesn't deal damage; it adds damage to your attacks.
- Reported failure: writing \`"Adds # to # Lightning Damage to Attacks"\` on a Bow recipe is WRONG — on a Bow it must be \`"Adds # to # Lightning Damage"\`. Same rule for all four damage types.

\`#\` is a literal placeholder for numeric ranges — do NOT substitute actual numbers in the recipe block. The lookup is by mod template, not specific roll.

If a mod you want isn't listed for the chosen base, that mod simply does NOT roll on that base — pick a different mod or a different base. NEVER fabricate.

There are ${totalMods} mod entries across ${cats.length} base categories.

${body.trim()}
`;
}
